apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
spec:
  ingressClassName: traefik
  rules:
    - host: hello-world.devops-ynov.com #host: hello-world.com #l'adresse du host ne correspond ppas à celle à laquelle on souhaite accéder.
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-service
                port:
                  number: 3000
