apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 2000
  selector:
    name: hello-world
  type: LoadBalancer
